"""empty message

Revision ID: 1e54a636e209
Revises: f35c8dca1e1a
Create Date: 2024-07-13 15:22:31.035660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e54a636e209'
down_revision = 'f35c8dca1e1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=16), nullable=False))

    # ### end Alembic commands ###
