"""empty message

Revision ID: 3f59fa58900d
Revises: b30920ebf5b0
Create Date: 2024-07-12 19:10:12.253878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f59fa58900d'
down_revision = 'b30920ebf5b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wholesalers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name', sa.String(length=64), nullable=True))
        batch_op.drop_column('company')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wholesalers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_column('company_name')

    # ### end Alembic commands ###
