"""empty message

Revision ID: 454c0c22e021
Revises: adfdea18c9c0
Create Date: 2024-07-13 09:06:25.072754

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '454c0c22e021'
down_revision = 'adfdea18c9c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checkpoints', sa.JSON(), nullable=True))
        batch_op.drop_column('locations')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locations', sqlite.JSON(), nullable=True))
        batch_op.drop_column('checkpoints')

    # ### end Alembic commands ###
