"""empty message

Revision ID: 592b59341710
Revises: c70b2031e599
Create Date: 2024-07-13 08:13:02.465963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '592b59341710'
down_revision = 'c70b2031e599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipment_id', sa.String(length=64), nullable=True))
        batch_op.create_foreign_key('None', 'shipments', ['shipment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('shipment_id')

    # ### end Alembic commands ###
