"""empty message

Revision ID: 8d4dd5fa3714
Revises: 2d5fa9879106
Create Date: 2024-07-13 07:37:36.116733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d4dd5fa3714'
down_revision = '2d5fa9879106'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('recipient_id', sa.String(length=64), nullable=True))
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('None', 'users', ['sender_id'], ['id'])
        batch_op.create_foreign_key('None', 'users', ['recipient_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('recipient_id')
        batch_op.drop_column('sender_id')

    # ### end Alembic commands ###
