"""empty message

Revision ID: cad4089b4a98
Revises: 3f59fa58900d
Create Date: 2024-07-12 19:26:00.010131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cad4089b4a98'
down_revision = '3f59fa58900d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manufacturers', schema=None) as batch_op:
        batch_op.drop_column('company_name')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name', sa.String(length=64), nullable=True))

    with op.batch_alter_table('wholesalers', schema=None) as batch_op:
        batch_op.drop_column('company_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wholesalers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name', sa.VARCHAR(length=64), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('company_name')

    with op.batch_alter_table('manufacturers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name', sa.VARCHAR(length=64), nullable=False))

    # ### end Alembic commands ###
