class Permission:
    PLACE_ORDER = 1
    VERIFY_PRODUCT = 2
    VIEW_RETAILER_PRODUCTS = 4
    VIEW_WHOLESALER_PRODUCTS = 8
    VIEW_MANUFACTURER_PRODUCTS = 16
    UPDATE_ORDER_STATUS = 32
    UPDATE_PRODUCT = 64
    GENERATE_QR_CODE = 128
    VIEW_DISTRIBUTION_DATA = 256
    VIEW_ALL_PRODUCTS = 512
